set(EXILE_CUSTOM_PATH_LEN CACHE STRING "custom max path len")
option(EXILE_DYNAMIC_PATH_LEN "enable windows long path(see in docs)" ON)
if(EXILE_DYNAMIC_PATH_LEN)
	add_compile_definitions(EXILE_DYNAMIC_PATH_LEN)
	message("[exile]: using dynamic path len")
	set(EX_DYN_PATH ON)
elseif(EXILE_CUSTOM_PATH_LEN)
	add_compile_definitions(EXILE_CUSTOM_PATH_LEN=${EXILE_CUSTOM_PATH_LEN})
	message("[exile]: using custom path len = ${EXILE_CUSTOM_PATH_LEN}")
	set(EX_DYN_PATH OFF)
elseif(ENABLE_EXILE_WIN_LONG_PATH)
	add_compile_definitions(EXILE_WIN_LONG_PATH)
	set(EX_DYN_PATH OFF)
else()
	set(EX_DYN_PATH OFF)
endif()